### ISSUE TITLE
你好大赵同学，刚看到你的github想问下你那个项目的问题可以吗？

### ISSUE THREAD

**Issue by Terabithia-Jay** [webyang-male/doc#1]
你好，请问《Nuxt3+Vue3实战在线教育SSR网站》这个项目的视频你有资源吗？有的话能否发一份给我，没有的话也没事，万分感谢！！！

**Comment by webyang-male** [comment]
> 你好，请问《Nuxt3+Vue3实战在线教育SSR网站》这个项目的视频你有资源吗？有的话能否发一份给我，没有的话也没事，万分感谢！！！

抱歉哈，这个没办法提供视频资源。
