### ISSUE TITLE
vue3-mallManage 这个仓库的后端在哪里呢?

### ISSUE THREAD

**Issue by HelloDS** [webyang-male/doc#2]
你好 博主，下载了你的 vue3-mallManage 仓库，发现了需要后端代码！可以吧后端的代码仓库共享吗？

**Comment by webyang-male** [comment]
> 你好 博主，下载了你的 vue3-mallManage 仓库，发现了需要后端代码！可以吧后端的代码仓库共享吗？

抱歉哈，前端代码开源已经是最大限度了。
